var a = 25;
var b = 36;
var additionResult = a + b;
var subtractionResult = a - b;
var divisionResult = a / b;
var multiplicationResult = a * b;
var moduloResult = b % a;
var increaseA = ++a;
var increaseB = ++b;
var decreaseA = --a;
var decreaseB = --b;

console.log("La suma de " + a + " + " + b + " es igual a ", additionResult);
console.log("La resta de " + a + " - " + b + " es igual a ", subtractionResult);
console.log("El resultado de la division de " + a + " entre " + b + " es igual a ", divisionResult);
console.log("La multiplicación de " + a + " por " + b + " es igual a ", multiplicationResult);
console.log("El residuo de " + b + " entre " + a + " es igual a", moduloResult);
console.log("La resultado de incrementar en 1 el valor de " + a + " es igual a ", increaseA);
console.log("La resultado de incrementar en 1 el valor de " + b + " es igual a ", increaseB);
console.log("La resultado de disminuir en 1 el valor de " + a + " es igual a ", decreaseA);
console.log("La resultado de disminuir en 1 el valor de " + b + " es igual a ", decreaseB);
